### ISSUE TITLE
uint8_t -> u8 as it's a linux kernel code convention

### ISSUE THREAD

**Issue by SerhiienkoRT** [kuzhylol/cst816x-driver#1]
https://github.com/kuzhylol/cst816x-driver/blob/25f0446f34f18c23ec431782f24b17786bfabe17/hynitron-cst816x.c#L54

**Comment by kuzhylol** [comment]
Thank you, resolved everywhere besides `struct cst816x_info`. 
I prefer to leave this part platform agnostic.
