### ISSUE TITLE
Consider to avoid using unspecified digits, prefer defines or constants to increase readability.

### ISSUE THREAD

**Issue by SerhiienkoRT** [kuzhylol/cst816x-driver#10]
https://github.com/kuzhylol/cst816x-driver/blob/25f0446f34f18c23ec431782f24b17786bfabe17/hynitron-cst816x.c#L201

**Comment by kuzhylol** [comment]
Those values are not documented, unfortunately.
That means I am not aware of exact register scheme and description.
