### ISSUE TITLE
Possible readability optimization

### ISSUE THREAD

**Issue by SerhiienkoRT** [kuzhylol/cst816x-driver#16]
https://github.com/kuzhylol/cst816x-driver/blob/ac0e130874446c6cbe319f9a1ef2ef9f5d0a1591/hynitron-cst816x.c#L122C1-L128C1

if (rc != ARRAY_SIZE(xfer)) {
    rc = (rc >= 0) ? -EIO : rc;
} else {
    rc = 0;
}

**Comment by kuzhylol** [comment]
Done
