### ISSUE TITLE
Driver should return an error when it couldn't allocate needed resources

### ISSUE THREAD

**Issue by SerhiienkoRT** [kuzhylol/cst816x-driver#4]
https://github.com/kuzhylol/cst816x-driver/blob/25f0446f34f18c23ec431782f24b17786bfabe17/hynitron-cst816x.c#L396

**Comment by SerhiienkoRT** [comment]
```
if (rc) {
  dev_err(dev, "IRQ probe err: %d\n", client->irq);
  return rc;
}

priv->irq = client->irq;
enable_irq(priv->irq);

```

**Comment by kuzhylol** [comment]
I'm following a single point return approach.
The error handling is being followed below:
```
if (rc)
        input_free_device(priv->input);
```

**Comment by SerhiienkoRT** [comment]
okay, but in case when the driver couldn't register IRQ and `devm_request_threaded_irq` returned error, your code will just notify about IRQ probe err and will still be in a memory. I guess it should unload itself.
