### ISSUE TITLE
remove is not implemented

### ISSUE THREAD

**Issue by SerhiienkoRT** [kuzhylol/cst816x-driver#6]
https://github.com/kuzhylol/cst816x-driver/blob/25f0446f34f18c23ec431782f24b17786bfabe17/hynitron-cst816x.c#L429

**Comment by SerhiienkoRT** [comment]
All the initialization is going in a probe function, freeing procedure should be done in a corresponding function -> cst816x_remove

**Comment by kuzhylol** [comment]
remove callback is not needed
