### ISSUE TITLE
Rely on what function returns if it isn't the function that you wrote

### ISSUE THREAD

**Issue by SerhiienkoRT** [kuzhylol/cst816x-driver#7]
https://github.com/kuzhylol/cst816x-driver/blob/25f0446f34f18c23ec431782f24b17786bfabe17/hynitron-cst816x.c#L108

**Comment by SerhiienkoRT** [comment]
`i2c_transfer` could return the code which could help you understanding the problem

**Comment by kuzhylol** [comment]
Fixed. Thank you
