### ISSUE TITLE
Use const to mark structures and variables that must not be modified inside a function

### ISSUE THREAD

**Issue by SerhiienkoRT** [kuzhylol/cst816x-driver#9]
https://github.com/kuzhylol/cst816x-driver/blob/25f0446f34f18c23ec431782f24b17786bfabe17/hynitron-cst816x.c#L90

**Comment by SerhiienkoRT** [comment]
That could apply to the whole codebase as a good practice

**Comment by kuzhylol** [comment]
Agree, the `const` qualifier was applied everywhere where it is possible. Thank you.
